container:
  image: cirrusci/android-sdk:27
  cpu: 4
  memory: 10G

check_android_task:
  gradle_cache:
    folder: ~/.gradle/caches
  check_script: ./gradlew build
    cleanup_before_cache_script:
    - rm -rf ~/.gradle/caches/$GRADLE_VERSION/
    - find ~/.gradle/caches/ -name "*.lock" -type f -delete
